name: SelfPrefix
main: net.meano.SelfPrefix.SelfPrefixMain
version: 0.1
author: Meano

commands:
  SelfPrefix:
    description: 
    usage: /SelfPrefix
    aliases: [sp]
    permission: SelfPrefix.Command
    permission-message: 指令不允许。

permissions:
  SelfPrefix.*:
    default: op
    children:
      SelfPrefix.Command: true
      SelfPrefix.Show: true
  SelfPrefix.Command:
      default: false
  SelfPrefix.Show:
      default: false